import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  resolve: {
    alias: {
      '@arcade-carnival/playables-adapter': resolve(__dirname, 'packages/playables-adapter/src/index.ts'),
      '@arcade-carnival/game-engine': resolve(__dirname, 'packages/game-engine/src/index.ts'),
    },
  },
  preview: {
    allowedHosts: true,
  },
  build: {
    rollupOptions: {
      input: {
        hub: resolve(__dirname, 'index.html'),
        embed: resolve(__dirname, 'embed.html'),
        'safe-cracker': resolve(__dirname, 'games/safe-cracker/index.html'),
        'brick-blitz': resolve(__dirname, 'games/brick-blitz/index.html'),
        'sky-hopper': resolve(__dirname, 'games/sky-hopper/index.html'),
        'crate-catch': resolve(__dirname, 'games/crate-catch/index.html'),
        'type-strike': resolve(__dirname, 'games/type-strike/index.html'),
        'memory-cards': resolve(__dirname, 'games/memory-cards/index.html'),
        'memory-boxes': resolve(__dirname, 'games/memory-boxes/index.html'),
        'pop-balloon': resolve(__dirname, 'games/pop-balloon/index.html'),
        'space-racer': resolve(__dirname, 'games/space-racer/index.html'),
        'virus-defense': resolve(__dirname, 'games/virus-defense/index.html'),
        'flappy-fish': resolve(__dirname, 'games/flappy-fish/index.html'),
        'game-2048': resolve(__dirname, 'games/game-2048/index.html'),
        'snake-eat': resolve(__dirname, 'games/snake-eat/index.html'),
        'bug-climb': resolve(__dirname, 'games/bug-climb/index.html'),
        'car-race': resolve(__dirname, 'games/car-race/index.html'),
        'drift-boss': resolve(__dirname, 'games/drift-boss/index.html'),
        'helix-jump': resolve(__dirname, 'games/helix-jump/index.html'),
        'square-bird': resolve(__dirname, 'games/square-bird/index.html'),
        'layers-roll': resolve(__dirname, 'games/layers-roll/index.html'),
        'mini-battles': resolve(__dirname, 'games/mini-battles/index.html'),
        'dino-runner': resolve(__dirname, 'games/dino-runner/index.html'),
        'snow-rider': resolve(__dirname, 'games/snow-rider/index.html'),
        'paper-basket': resolve(__dirname, 'games/paper-basket/index.html'),
        'potion-merge': resolve(__dirname, 'games/potion-merge/index.html'),
        'mahjong-paper': resolve(__dirname, 'games/mahjong-paper/index.html'),
        'subway-runner': resolve(__dirname, 'games/subway-runner/index.html'),
        'prism-laser': resolve(__dirname, 'games/prism-laser/index.html'),
        'rainbow-draw': resolve(__dirname, 'games/rainbow-draw/index.html'),
        'firework-pop': resolve(__dirname, 'games/firework-pop/index.html'),
        'fruit-flood': resolve(__dirname, 'games/fruit-flood/index.html'),
        'snow-smash': resolve(__dirname, 'games/snow-smash/index.html'),
        'mosquito-swat': resolve(__dirname, 'games/mosquito-swat/index.html'),
        'tic-tac-toe': resolve(__dirname, 'games/tic-tac-toe/index.html'),
        'bubble-pop': resolve(__dirname, 'games/bubble-pop/index.html'),
        'pop-it': resolve(__dirname, 'games/pop-it/index.html'),
        'soap-carve': resolve(__dirname, 'games/soap-carve/index.html'),
        'hydraulic-crush': resolve(__dirname, 'games/hydraulic-crush/index.html'),
        'sand-zen': resolve(__dirname, 'games/sand-zen/index.html'),
        'liquid-sort': resolve(__dirname, 'games/liquid-sort/index.html'),
        'fidget-spin': resolve(__dirname, 'games/fidget-spin/index.html'),
        'grass-mow': resolve(__dirname, 'games/grass-mow/index.html'),
        'koi-pond': resolve(__dirname, 'games/koi-pond/index.html'),
        'tank-1990': resolve(__dirname, 'games/tank-1990/index.html'),
        'kirby-adventure': resolve(__dirname, 'games/kirby-adventure/index.html'),
        'legend-of-kage': resolve(__dirname, 'games/legend-of-kage/index.html'),
      },
    },
  },
});
